export const QUESTION_CONTRACT_VERSION = '2026-09-21';

const eventContext = {
  year: 2022,
  eventId: 'event:2022:italian-grand-prix',
  sessionId: null,
  driverId: null,
  constructorId: null,
};

export const questionContractScenarios = [
  {
    id: 'event-winner-2022-italian',
    family: 'event winner',
    mode: 'deterministic',
    questions: ['Who won the 2022 Italian Grand Prix?', 'Who won the 2022 Italian GP?'],
    constraints: { event: 'Italian Grand Prix', year: 2022 },
    intent: 'event_winner',
    derive: 'eventWinner',
  },
  {
    id: 'event-podium-context',
    family: 'event podium',
    mode: 'deterministic',
    questions: ['Who finished on the podium?'],
    context: eventContext,
    constraints: { event: 'Italian Grand Prix', year: 2022, metric: 'podium' },
    intent: 'event_podium',
    derive: 'eventPodium',
  },
  {
    id: 'event-fastest-lap-context',
    family: 'fastest lap',
    mode: 'deterministic',
    questions: ['Who set the fastest lap?'],
    context: eventContext,
    constraints: { event: 'Italian Grand Prix', year: 2022, metric: 'fastest_lap' },
    intent: 'event_fastest_lap',
    derive: 'eventFastestLap',
  },
  {
    id: 'event-pole-context',
    family: 'pole position',
    mode: 'deterministic',
    questions: ['Who was on pole?'],
    context: eventContext,
    constraints: { event: 'Italian Grand Prix', year: 2022, metric: 'pole' },
    intent: 'event_pole',
    derive: 'eventPole',
  },
  {
    id: 'event-circuit-2022-italian',
    family: 'event circuit',
    mode: 'deterministic',
    questions: [
      'Which circuit hosted the 2022 Italian Grand Prix?',
      'Where was the 2022 Italian Grand Prix held?',
      'What circuit hosted the 2022 Italian GP?',
    ],
    constraints: { event: 'Italian Grand Prix', year: 2022, metric: 'circuit' },
    intent: 'event_circuit',
    derive: 'eventCircuit',
  },
  {
    id: 'driver-season-wins-2023-max',
    family: 'driver season wins',
    mode: 'deterministic',
    questions: [
      'How many races did Max Verstappen win in 2023?',
      'How many wins did Max Verstappen have in 2023?',
      'How many Grand Prix victories did Max Verstappen have during the 2023 season?',
    ],
    constraints: { driver: 'Max Verstappen', metric: 'race_wins', year: 2023 },
    intent: 'driver_race_wins_season',
    derive: 'driverSeasonWins',
  },
  {
    id: 'driver-relative-wins-last-year',
    family: 'relative driver season wins',
    mode: 'deterministic',
    questions: ['How many races did Max Verstappen win last year?'],
    constraints: { driver: 'Max Verstappen', metric: 'race_wins', period: 'last_year' },
    intent: 'driver_race_wins_season',
    derive: 'driverRelativeWins',
  },
  {
    id: 'driver-career-wins-max',
    family: 'driver career wins',
    mode: 'deterministic',
    questions: ['How many races has Max Verstappen won?'],
    constraints: { driver: 'Max Verstappen', metric: 'race_wins', scope: 'career' },
    intent: 'driver_race_wins',
    derive: 'driverCareerWins',
  },
  {
    id: 'driver-career-podiums-max',
    family: 'driver podiums',
    mode: 'deterministic',
    questions: ['How many podiums does Max Verstappen have?'],
    constraints: { driver: 'Max Verstappen', metric: 'podiums', scope: 'career' },
    intent: 'driver_stat',
    derive: 'driverMetric',
    metric: 'podiums',
  },
  {
    id: 'driver-career-poles-max',
    family: 'driver poles',
    mode: 'deterministic',
    questions: ['How many poles does Max Verstappen have?'],
    constraints: { driver: 'Max Verstappen', metric: 'poles', scope: 'career' },
    intent: 'driver_stat',
    derive: 'driverMetric',
    metric: 'poles',
  },
  {
    id: 'driver-career-fastest-laps-max',
    family: 'driver fastest laps',
    mode: 'deterministic',
    questions: ['How many fastest laps does Max Verstappen have?'],
    constraints: { driver: 'Max Verstappen', metric: 'fastest_laps', scope: 'career' },
    intent: 'driver_stat',
    derive: 'driverMetric',
    metric: 'fastest_laps',
  },
  {
    id: 'driver-career-starts-max',
    family: 'driver starts',
    mode: 'deterministic',
    questions: ['How many race starts does Max Verstappen have?'],
    constraints: { driver: 'Max Verstappen', metric: 'race_starts', scope: 'career' },
    intent: 'driver_stat',
    derive: 'driverMetric',
    metric: 'race_starts',
  },
  {
    id: 'driver-status-retirements-max',
    family: 'driver status metric',
    mode: 'deterministic',
    questions: ['How many retirements does Max Verstappen have?'],
    constraints: { driver: 'Max Verstappen', metric: 'retirements', scope: 'career' },
    intent: 'driver_stat',
    derive: 'driverMetric',
    metric: 'retirements',
  },
  {
    id: 'finishing-position-second',
    family: 'generalized finishing position',
    mode: 'deterministic',
    questions: [
      'Which driver has had the most second-place finishes?',
      'Which driver has had the most finishes in position 2?',
    ],
    constraints: { metric: 'finishing_position_leader', position: 2, scope: 'career' },
    intent: 'driver_finishing_position',
    derive: 'finishingPosition',
    position: 2,
  },
  {
    id: 'finishing-position-fifth-2023',
    family: 'generalized finishing position',
    mode: 'deterministic',
    questions: [
      'Which driver has had the most fifth-place finishes in 2023?',
      'Which driver has had the most finishes in position 5 during 2023?',
    ],
    constraints: { metric: 'finishing_position_leader', position: 5, year: 2023 },
    intent: 'driver_finishing_position',
    derive: 'finishingPosition',
    position: 5,
    fromYear: 2023,
    toYear: 2023,
  },
  {
    id: 'driver-wins-comparison',
    family: 'driver comparison',
    mode: 'deterministic',
    questions: ['How many wins does Max Verstappen have compared to Lewis Hamilton?'],
    constraints: {
      metric: 'race_wins',
      scope: 'career',
      driver: 'Max Verstappen',
      comparisonDriver: 'Lewis Hamilton',
    },
    intent: 'driver_race_wins_comparison',
    derive: 'driverWinsComparison',
  },
  {
    id: 'driver-championship-history',
    family: 'championship standings',
    mode: 'deterministic',
    questions: ['Was Max Verstappen ever a world champion?'],
    constraints: { driver: 'Max Verstappen', metric: 'championships', scope: 'career' },
    intent: 'driver_stat',
    derive: 'driverChampionships',
  },
  {
    id: 'driver-constructor-participation',
    family: 'constructor participation/history',
    mode: 'deterministic',
    questions: ['How many races did Lewis Hamilton start for Mercedes?'],
    constraints: {
      driver: 'Lewis Hamilton',
      constructor: 'Mercedes',
      metric: 'race_starts',
      scope: 'career',
    },
    intent: 'driver_constructor_race_starts',
    derive: 'driverConstructorStarts',
  },
  {
    id: 'circuit-history-monza',
    family: 'circuit race history',
    mode: 'deterministic',
    questions: ['Who won the last three races at Monza?'],
    constraints: { circuit: 'Monza', metric: 'race_winners', limit: 3, period: 'last_three' },
    intent: 'circuit_race_winners',
    derive: 'circuitHistory',
    circuit: 'Monza',
    limit: 3,
  },
  {
    id: 'country-history-italy',
    family: 'country race history',
    mode: 'deterministic',
    questions: ['Who won the last two races in Italy?'],
    constraints: { country: 'Italy', metric: 'race_winners', limit: 2, period: 'last_two' },
    intent: 'country_race_winners',
    derive: 'countryHistory',
    country: 'Italy',
    limit: 2,
  },
  {
    id: 'pit-stops-sparse-publication',
    family: 'pit stops',
    mode: 'deterministic',
    questions: ['Who made the most pit stops at the 2022 Italian Grand Prix?'],
    constraints: { event: 'Italian Grand Prix', year: 2022, metric: 'pit_stops' },
    intent: 'event_pit_stops',
    derive: 'pitStopsUnavailable',
    unavailableReason: 'PIT_STOPS_NOT_PUBLISHED',
  },
  {
    id: 'weather-sparse-publication',
    family: 'weather unavailable boundary',
    mode: 'deterministic',
    questions: ['What was the weather at the 2022 Italian Grand Prix?'],
    constraints: { event: 'Italian Grand Prix', year: 2022, metric: 'weather_summary' },
    intent: 'event_session_metric',
    derive: 'unavailableDataset',
    datasetPrefix: 'weather:',
    unavailableReason: 'WEATHER_NOT_PUBLISHED',
  },
  {
    id: 'tyre-compound-sparse-publication',
    family: 'tyre and compound constraints',
    mode: 'deterministic',
    questions: [
      'How many laps did Max Verstappen run on soft tyres at the 2022 Italian Grand Prix?',
    ],
    constraints: {
      event: 'Italian Grand Prix',
      year: 2022,
      driver: 'Max Verstappen',
      metric: 'tyre_laps',
      compound: 'soft',
    },
    intent: 'event_session_metric',
    derive: 'unavailableDataset',
    datasetPrefix: 'stints:',
    unavailableReason: 'STINTS_NOT_PUBLISHED',
  },
  {
    id: 'race-control-sparse-publication',
    family: 'race control unavailable boundary',
    mode: 'deterministic',
    questions: ['How many safety cars were there at the 2022 Italian Grand Prix?'],
    constraints: { event: 'Italian Grand Prix', year: 2022, metric: 'safety_car_events' },
    intent: 'event_session_metric',
    derive: 'unavailableDataset',
    datasetPrefix: 'race-control:',
    unavailableReason: 'RACE_CONTROL_NOT_PUBLISHED',
  },
  {
    id: 'overtakes-sparse-publication',
    family: 'overtakes unavailable boundary',
    mode: 'deterministic',
    questions: ['Who made the most overtakes at the 2022 Italian Grand Prix?'],
    constraints: { event: 'Italian Grand Prix', year: 2022, metric: 'most_overtakes' },
    intent: 'event_session_metric',
    derive: 'unavailableDataset',
    datasetPrefix: 'overtakes:',
    unavailableReason: 'OVERTAKES_NOT_PUBLISHED',
  },
  {
    id: 'future-race-unavailable',
    family: 'future race',
    mode: 'deterministic',
    questions: ['Who won the 2026 Azerbaijan Grand Prix?'],
    constraints: { event: 'Azerbaijan Grand Prix', year: 2026, metric: 'winner' },
    intent: 'event_winner',
    derive: 'eventWinner',
    unavailableReason: 'WINNER_NOT_PUBLISHED',
  },
  {
    id: 'round-snapshot-interpreter-boundary',
    family: 'round standings snapshot',
    mode: 'interpreter-boundary',
    questions: ['Who led after round 10 in 2023?'],
    constraints: { year: 2023, round: 10, metric: 'standings_leader' },
    intent: 'season_round_standings',
    expectedStatus: 'unavailable',
    unavailableReason: 'QUESTION_INTERPRETER_DISABLED',
  },
  {
    id: 'season-calendar-interpreter-boundary',
    family: 'season calendar and coverage',
    mode: 'interpreter-boundary',
    questions: ['How many events were in the 2022 season?'],
    constraints: { year: 2022, metric: 'season_event_count' },
    intent: 'season_calendar_summary',
    expectedStatus: 'unavailable',
    unavailableReason: 'QUESTION_INTERPRETER_DISABLED',
  },
  {
    id: 'unknown-driver-context',
    family: 'unknown entity',
    mode: 'deterministic',
    questions: ['How many podiums does Max Verstappen have?'],
    context: {
      year: null,
      eventId: null,
      sessionId: null,
      driverId: 'driver:not-published',
      constructorId: null,
    },
    constraints: { driver: 'driver:not-published', metric: 'podiums' },
    intent: 'driver_stat',
    expectedStatus: 'clarification',
    derive: 'unknownDriverContext',
  },
  {
    id: 'ambiguous-event-season',
    family: 'ambiguous event constraint',
    mode: 'deterministic',
    questions: ['Which circuit hosted the Italian Grand Prix?'],
    constraints: { event: 'Italian Grand Prix', year: null, metric: 'circuit' },
    intent: 'event_circuit',
    expectedStatus: 'clarification',
  },
  {
    id: 'invalid-finishing-position',
    family: 'invalid constraint',
    mode: 'deterministic',
    questions: ['Which driver has the most 101st-place finishes?'],
    constraints: { metric: 'finishing_position_leader', position: 101 },
    intent: 'driver_finishing_position',
    expectedStatus: 'unsupported',
    unavailableReason: 'FINISHING_POSITION_INVALID',
  },
  {
    id: 'unknown-event-circuit',
    family: 'unknown event',
    mode: 'deterministic',
    questions: ['Which circuit hosted the 2022 Mars Grand Prix?'],
    constraints: { event: 'Mars Grand Prix', year: 2022, metric: 'circuit' },
    intent: 'event_circuit',
    expectedStatus: 'unavailable',
    derive: 'unknownEvent',
    unavailableReason: 'EVENT_NOT_PUBLISHED',
  },
];
